---
apiVersion: v1
kind: Service
metadata:
  name: jsbtodo-service
  labels:
    app: jsbtodo-app
spec:
  selector:
    app: jsbtodo-app
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsbtodo-deploy
spec:
  selector:
    matchLabels:
      app: jsbtodo-app
  replicas: 1
  template:
    metadata:
      name: my-deployment
      labels:
        app: jsbtodo-app
    spec:
      containers:
        - name: jsbtodo
          image: sbathuru/java-springboot-todo:latest
          ports:
            - containerPort: 8080
#  http://3.6.94.232:32000/jsbtodo/
