name: Java CI with Gradle

on:
  push:
    branches: [master]

jobs:
  java-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Build with Maven
        run: mvn -B package -Pcoverage

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: java-springboot-todo-1.0.0-SNAPSHOT.jar
          path: ./target/*.jar

      - name: Send email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: srinivas.bathuru@gmail.com
          # from email name
          from: srinivas.bathuru@gmail.com
